name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '14.x', '16.x' ]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install deps
        run: yarn install --frozen-lockfile --silent
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:dev
          command: npm run e2e:ci
          browser: chrome
          headless: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          
      - name: Cypress Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/cypress/screenshots
