name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, lint, and test on Node 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 5

      - name: Install deps
        run: yarn install --frozen-lockfile --silent
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:dev
          command: npm run e2e:ci
          browser: chrome
          headless: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          
      - name: Cypress Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/cypress/screenshots
